# Generated by Django 3.2.4 on 2021-07-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uid',
        ),
        migrations.AddField(
            model_name='comment',
            name='uname',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
